In [28]:
import tensorflow as tf
tf.reset_default_graph()
var1 = tf.get_variable('var1',shape=[2,],initializer=tf.ones_initializer)
var2 = tf.get_variable('var2',shape=[],initializer=tf.ones_initializer)
var2= tf.multiply(var2,2)
res = tf.add(tf.multiply([1.,1.],var1),var2)
grad = tf.gradients(res,var2)
weight_0 = tf.get_variable('weigth_0',shape=[],initializer=tf.ones_initializer)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(var1))
    print(sess.run(var2))
    print(sess.run(res))
    print(sess.run(grad))
    

[1. 1.]
2.0
[3. 3.]
[2.0]


In [138]:
import tensorflow as tf
from sklearn.feature_extraction import DictVectorizer
import numpy as np

tf.reset_default_graph()
train = [
    {"user": "1", "item": "5", "age": 19},
    {"user": "2", "item": "43", "age": 33},
    {"user": "3", "item": "20", "age": 55},
    {"user": "4", "item": "10", "age": 20},
]
# train = [
#         {"user": "1", "age": 19},
#         {"user": "2", "age": 33},
#         {"user": "3", "age": 55},
#         {"user": "4", "age": 20},
#     ]
v = DictVectorizer()
print(v.fit_transform(train).toarray())
X = tf.constant(v.fit_transform(train).toarray(), tf.float32)

y = tf.constant(np.array([[1], [1], [-1], [-1]]), dtype=tf.float32)
weight_0 = tf.get_variable('weight_0', shape=[1], initializer=tf.zeros_initializer)
weights = tf.get_variable('weights', shape=[X.shape[1], 1], initializer=tf.ones_initializer)
v_matrix1 = tf.get_variable('vectors1', shape=[2, X.shape[1]], initializer=tf.ones_initializer)
v_matrix2 = tf.get_variable('vectors2', shape=[2, X.shape[1]], initializer=tf.ones_initializer)
y_ = (weight_0 + tf.matmul(X, weights))

from itertools import combinations

for f_indices in combinations(range(X.shape[1]), 2):
    f_prod, v_prod = tf.ones((4, 1)), tf.ones((2, 1))
    for f_index in f_indices:
        f_prod = tf.multiply(f_prod, X[:, f_index:f_index + 1])
        v_prod = tf.multiply(v_prod, v_matrix1[:, f_index:f_index + 1])
    y_ = tf.add(y_, tf.multiply(f_prod, tf.reduce_sum(v_prod)))

for f_indices in combinations(range(X.shape[1]), 3):
    f_prod, v_prod = tf.ones((4, 1)), tf.ones((2, 1))
    for f_index in f_indices:
        f_prod = tf.multiply(f_prod, X[:, f_index:f_index + 1])
        v_prod = tf.multiply(v_prod, v_matrix2[:, f_index:f_index + 1])
    y_ = tf.add(y_, tf.multiply(f_prod, tf.reduce_sum(v_prod)))

loss = tf.maximum(0., 1 - tf.multiply(y, y_))
loss = tf.reduce_mean(loss)
grad = tf.gradients(loss, v_matrix2)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y_))
    print(sess.run(loss))
    print(sess.run(grad))


[[19.  0.  0.  0.  1.  1.  0.  0.  0.]
 [33.  0.  0.  1.  0.  0.  1.  0.  0.]
 [55.  0.  1.  0.  0.  0.  0.  1.  0.]
 [20.  1.  0.  0.  0.  0.  0.  0.  1.]]


[[137.]
 [235.]
 [389.]
 [144.]]


133.75


[array([[18.75,  5.  , 13.75,  0.  ,  0.  ,  0.  ,  0.  , 13.75,  5.  ],
       [18.75,  5.  , 13.75,  0.  ,  0.  ,  0.  ,  0.  , 13.75,  5.  ]],
      dtype=float32)]


In [127]:
tf.reset_default_graph()
train = [
    {"user": "1", "item": "5", "age": 19},
    {"user": "2", "item": "43", "age": 33},
    {"user": "3", "item": "20", "age": 55},
    {"user": "4", "item": "10", "age": 20},
]
v = DictVectorizer()
print(v.fit_transform(train).toarray())
X = tf.constant(v.fit_transform(train).toarray(), tf.float32)
f_prod,v_prod = tf.ones((2,1)),tf.ones((4,1))
res = tf.multiply(v_prod,X[:,2])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    print(sess.run(res))

[[19.  0.  0.  0.  1.  1.  0.  0.  0.]
 [33.  0.  0.  1.  0.  0.  1.  0.  0.]
 [55.  0.  1.  0.  0.  0.  0.  1.  0.]
 [20.  1.  0.  0.  0.  0.  0.  0.  1.]]
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]
